services:
  db-dev:
    image: postgres:15
    container_name: db_dev
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: banco_desenvolvimento 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d banco_desenvolvimento"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    container_name: db_test
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: banco_teste
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d banco_teste"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"

volumes:
  pgdata: